spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000
    fault_tolerance:  0.001
    warn_limit: 7
    batch_size: 10000
  rule:
    #远程规则
    remote:
      - 'https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts' #1024网站及澳门皇家赌场及恶意广告主机列表
      - 'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad.txt' #halflife-list
      - 'https://raw.githubusercontent.com/lingeringsound/10007_auto/master/adb.txt' #保留广告奖励
      - 'https://www.xlxbk.cn/allow.txt' #白名单
      - 'https://code.gitlink.org.cn/damengzhu/banad/raw/branch/main/jiekouAD.txt/' #酷安大萌主
      - 'http://sub.adtchrome.com/adt-chinalist-easylist.txt' #广告终结者使用的拦截规则
      - 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt' #AdRules
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
#      regex.txt:
#        - REGEX
#      domain.txt:
#        - DOMAIN
      modify.txt:
        - MODIFY
