{ spring: { application: { name: 'DD-AD' }, profiles: { active: 'prod' } },
  logging: { file: { path: './logs' } },
  application: 
   { config: 
      { expected_quantity: 2000000,
        fault_tolerance: 0.001,
        warn_limit: 7,
        batch_size: 10000 },
     rule: 
      { remote: 
         [ 'https://adaway.org/hosts.txt',
           'https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt',
           'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts',
           'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt',
           'https://raw.githubusercontent.com/sbwml/halflife-list/master/ad-pc.txt',
           'https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts',
           'https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad.txt',
           'https://raw.githubusercontent.com/lingeringsound/10007_auto/master/adb.txt' ],
        local: [ 'mylist.txt' ] },
     output: 
      { file_header: '[ADFS Adblock List]\n! Title: ${name}\n! Last Modified: ${date}\n! Homepage: https://github.com/afwfv/DD-AD.git\n',
        path: 'rule',
        '文件': 
         { 'all.txt': [ 'DOMAIN', 'REGEX', 'MODIFY', 'HOSTS' ],
           'dns.txt': [ 'DOMAIN', 'REGEX', 'HOSTS' ],
           'hosts.txt': [ 'HOSTS' ],
           'regex.txt': [ 'REGEX' ],
           'domain.txt': [ 'DOMAIN' ],
           'modify.txt': [ 'MODIFY' ] } } } }
